name = "baron-scheduler"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
ADMIN_PASSWORD = "BaronAdmin"

[[d1_databases]]
binding = "DB"
database_name = "baron-scheduler-db"
database_id = "bed3b521-a506-4c80-9fa7-5fabebb9dd85"
